#!/usr/bin/env bash
set -euxo pipefail

triplet=${1}
dest=${2:-"/opt/${triplet}"}
mkdir -p "${dest}"

URL="https://github.com/binarylandia/build_crosstool-ng/releases/download/2024-12-08_02-28-06/gcc-14.2.0-${triplet}-2024-12-08_02-28-06.tar.xz"

curl -fsSL "${URL}" \
  | pixz -dp "$(nproc)" \
  | tar -C "${dest}" -x

ls "${dest}/bin/${triplet}-gcc"
"${dest}/bin/${triplet}-gcc" -v

ls "${dest}/bin/${triplet}-gcc-ar"
"${dest}/bin/${triplet}-gcc-ar" --version

if [[ "${triplet}" =~ (mingw|windows) ]]; then
  # HACK: sysroot in MinGW GCC is nested under additional `mingw/` path segment, copy it upstairs to avoid having to
  # set different sysroot variables for Linux and Windows
  cp -r "${dest}/x86_64-w64-mingw32/sysroot/mingw/"* "${dest}/x86_64-w64-mingw32/sysroot"/
fi

gcc_triplet="$("${dest}/bin/${triplet}-gcc" -dumpmachine)"
if [ "${gcc_triplet}" != "${triplet}" ]; then
  echo "$0: GCC target triplet '${gcc_triplet}' does not match requested '${triplet}'" >&2
  exit 1
fi
