#!/usr/bin/env bash
set -euxo pipefail

triplet=${1}
dest=${2:-"/opt/${triplet}"}
mkdir -p "${dest}"

URL="https://github.com/binarylandia/build_crosstool-ng/releases/download/2024-12-08_02-28-06/gcc-14.2.0-${triplet}-2024-12-08_02-28-06.tar.xz"
REFERER=$(echo "${URL}" | sed -e 's|^[^/]*//||' -e 's|/.*$||')
USER_AGENT="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
JOBS=16
TEMP_FILE=$(mktemp)
aria2c \
  --allow-overwrite=true \
  --allow-piece-length-change=true \
  --console-log-level=error \
  --continue=false \
  --download-result=hide \
  --file-allocation=none \
  --follow-metalink=mem \
  --max-concurrent-downloads=${JOBS} \
  --max-connection-per-server=${JOBS} \
  --max-tries=3 \
  --min-split-size=1M \
  --referer="${REFERER}" \
  --split=${JOBS} \
  --summary-interval=0 \
  --timeout=120 \
  --user-agent="${USER_AGENT}" \
  -o "${TEMP_FILE}" \
  "${URL}" \
  >/dev/null
pixz -dp "$(nproc)" < "${TEMP_FILE}" | tar -C "${dest}" -x
rm -f "${TEMP_FILE}"

ls "${dest}/bin/${triplet}-gcc"
"${dest}/bin/${triplet}-gcc" -v

ls "${dest}/bin/${triplet}-gcc-ar"
"${dest}/bin/${triplet}-gcc-ar" --version

if [[ "${triplet}" =~ (mingw|windows) ]]; then
  # HACK: sysroot in MinGW GCC is nested under additional `mingw/` path segment, copy it upstairs to avoid having to
  # set different sysroot variables for Linux and Windows
  cp -r "${dest}/x86_64-w64-mingw32/sysroot/mingw/"* "${dest}/x86_64-w64-mingw32/sysroot"/
fi

gcc_triplet="$("${dest}/bin/${triplet}-gcc" -dumpmachine)"
if [ "${gcc_triplet}" != "${triplet}" ]; then
  echo "$0: GCC target triplet '${gcc_triplet}' does not match requested '${triplet}'" >&2
  exit 1
fi
