#!/usr/bin/env bash
set -euxo pipefail

dest=${1:-"/usr/local"}
mkdir -p "${dest}"

URL="https://github.com/binarylandia/build_llvm/releases/download/llvm-19.1.5-2024-12-03_22-45-06/llvm-19.1.5-2024-12-03_22-45-06.tar.xz"
REFERER=$(echo "${URL}" | sed -e 's|^[^/]*//||' -e 's|/.*$||')
USER_AGENT="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
JOBS=16
TEMP_FILE=$(mktemp)
aria2c \
  --allow-overwrite=true \
  --allow-piece-length-change=true \
  --console-log-level=error \
  --continue=false \
  --download-result=hide \
  --file-allocation=none \
  --follow-metalink=mem \
  --max-concurrent-downloads=${JOBS} \
  --max-connection-per-server=${JOBS} \
  --max-tries=3 \
  --min-split-size=1M \
  --referer="${REFERER}" \
  --split=${JOBS} \
  --summary-interval=0 \
  --timeout=120 \
  --user-agent="${USER_AGENT}" \
  -o "${TEMP_FILE}" \
  "${URL}" \
  >/dev/null
pixz -dp "$(nproc)" < "${TEMP_FILE}" | tar -C "${dest}" -x
rm -f "${TEMP_FILE}"

ls "${dest}/bin/clang"
"${dest}/bin/clang" -v

ls "${dest}/bin/llvm-ar"
"${dest}/bin/llvm-ar" --version
