#!/usr/bin/env bash
# shellcheck disable=SC2155
set -euo pipefail
trap "exit" INT
# shellcheck source=./../../dev/lib/utils.sh
source "${BASH_SOURCE%/*}/../../dev/lib/utils.sh"

export CROSS_COMPILE="${CROSS_COMPILE:?}"
export BUILD_TIME="${BUILD_TIME:?}"
export TASK_NAME="${TASK_NAME:?}"
export TASK_DIR="${TASK_DIR:?}"
export BUILD_DIR="${BUILD_DIR:?}"
export INSTALL_DIR="${INSTALL_DIR:?}"
export OUT_DIR="${OUT_DIR:?}"

NAME="${TASK_NAME}"
REPO_URL="https://github.com/iqtree/iqtree2"
VERSION="2.3.6"

build_dir="$(abspath "${BUILD_DIR}")"
install_dir="$(abspath "${INSTALL_DIR}")"
out_dir="$(abspath "${OUT_DIR}")"

mkdir -p "${build_dir}" "${install_dir}" "${out_dir}"
pushd "${build_dir}" >/dev/null
{
  src_dir="${NAME}-${VERSION}"


  if [ ! -d "${src_dir}" ]; then
    nicely git clone --quiet --recursive --depth=1 -b "v${VERSION}" "${REPO_URL}" "${src_dir}"

    mkdir -p "eigen"
    curl -fsSL "https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.gz" | tar -C "eigen" --strip-components=1 -xz

    pushd "eigen" >/dev/null
    {
      nicely cmake -S "." -B "build" \
        -Wno-dev -Wno-deprecated \
        -DCMAKE_BUILD_TYPE="Release" \
        -DCMAKE_INSTALL_INCLUDEDIR="include" \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="${install_dir}" \
        -DCMAKE_FIND_DEBUG_MODE="OFF" \
        -DCMAKE_VERBOSE_MAKEFILE="OFF" \
        2>&1 | log "${build_dir}/build.log"

      nicely cmake --build "build" --parallel="${JOBS}" -- 2>&1 | log "${build_dir}/build.log"

      nicely cmake --install "build" 2>&1 | log "${build_dir}/build.log"
    }
    popd >/dev/null

  fi

  pushd "${src_dir}" >/dev/null
  {
#    # Comment-out hardcoded instruction sets. We set target arch flags in CFLAGS & CXXFLAGS
#    sed -i "s|add_compile_options(-msse|#add_compile_options(-msse|g" "CMakeLists.txt"
#    sed -i "s|add_compile_options(-neon|#add_compile_options(-neon|g" "CMakeLists.txt"
#    sed -i "s|add_compile_options(-march=armv8-a|#add_compile_options(-march=armv8-a|g" "CMakeLists.txt"
#    sed -i "s|add_compile_options(-march=native|#add_compile_options(-march=native|g" "CMakeLists.txt"
#
#    # Disable tests
#    sed -i "s|add_subdirectory(unittest)|#add_subdirectory(unittest)|g" "CMakeLists.txt"
#    sed -i 's|FetchContent_MakeAvailable(googletest)|#FetchContent_MakeAvailable(googletest)|g' "CMakeLists.txt"
#
#    # Comment-out LTO settings
#    sed -i "s|set(CMAKE_INTERPROCEDURAL_OPTIMIZATION|#set(CMAKE_INTERPROCEDURAL_OPTIMIZATION|g" "CMakeLists.txt"
#
#    # Remove dangerous/broken settings
#    sed -i 's|include_directories(after system "/usr/local/include")|#include_directories(after system "/usr/local/include")|g' "CMakeLists.txt"
#    sed -i 's|set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -lomp")|#set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -lomp")|g' "CMakeLists.txt"
#
##    export CFLAGS="${CFLAGS} -fopenmp"
##    export CXXFLAGS="${CFLAGS} -fopenmp"
#    export CMAKE_C_COMPILER_LAUNCHER="ccache"
#    export CMAKE_CXX_COMPILER_LAUNCHER="ccache"
#
#    export CC="${GCC}"
#    export CXX="${GXX}"
##    export LD="${CLANGXX}"
#
#    export LDFLAGS="
#      -lcrt3.o \
#      -lm \
#      -lc \
#    "
##      -lcrtfastmath.o \
##      -lcrttme.o \
##      -lcrttms.o \
##      -llibcaf_single.a \
##      -llibcaf_single.la \
##      -llibemutls_w.a \
##      -llibgcc.a \
##      -llibgcc_eh.a \
##      -llibgcov.a \
##      -llibheapt_w.a \
#
##    export CMAKE_PREFIX_PATH="${CMAKE_PREFIX_PATH:+$CMAKE_PREFIX_PATH:}/opt/osxcross/lib/gcc/aarch64-apple-darwin20.2/14.2.0:/opt/osxcross/aarch64-apple-darwin20.2"
#
##    export CMAKE_C_COMPILER="${GCC}"
##    export CMAKE_CXX_COMPILER="${GXX}"
##    export CMAKE_LINKER="${CLANGXX}"
#
#    export CMAKE_SYSTEM_NAME="Darwin"
#    export CMAKE_SYSTEM_PROCESSOR="aarch64"
#
#    export CMAKE_OSX_SYSROOT="${CROSS_SYSROOT}"
#
#    export OSXCROSS_HOST="${CROSS_APPLE_TRIPLET}"
##    export CMAKE_TOOLCHAIN_FILE="/opt/osxcross/toolchain.cmake"


    export EIGEN3_INCLUDE_DIR="${install_dir}/eigen"

    nicely cmake -S "." -B "build" \
      -Wno-dev -Wno-deprecated \
      -DCMAKE_BUILD_TYPE="Release" \
      -DCMAKE_INSTALL_INCLUDEDIR="include" \
      -DCMAKE_INSTALL_LIBDIR="lib" \
      -DCMAKE_INSTALL_PREFIX="${install_dir}" \
      -DCMAKE_FIND_DEBUG_MODE="OFF" \
      -DCMAKE_VERBOSE_MAKEFILE="ON" \
      \
      -DCMAPLE_FLAGS=static \
      \
      -DBUILD_GMOCK="OFF" \
      -DINSTALL_GTEST="OFF" \
      2>&1 | log "${build_dir}/build.log"

    nicely cmake --build "build" --parallel="${JOBS}" -- 2>&1 | log "${build_dir}/build.log"

    nicely cmake --install "build" 2>&1 | log "${build_dir}/build.log"

#    # Remove example data
#    nicely rm -rf "${install_dir}/example.maple" "${install_dir}/tree.nwk"
#
#    # Strip binaries correctly
#    nicely mv "${install_dir}/bin" "${install_dir}/bin.old"
#    for f in $(ls -1 "${install_dir}/bin.old"); do
#      nicely install -D -m 0755 -s --strip-program="${STRIP:-strip}" "${install_dir}/bin.old/$f" "${install_dir}/bin/$f"
#    done
#    rm -rf "${install_dir}/bin.old"

    package_all "${install_dir}" "${out_dir}/${NAME}-${VERSION}-static-${CROSS_COMPILE}-${BUILD_TIME}"
  }
  popd >/dev/null
}
popd >/dev/null
