#!/usr/bin/env bash
# shellcheck disable=SC2155
set -euo pipefail
trap "exit" INT
# shellcheck source=./../../dev/lib/utils.sh
source "${BASH_SOURCE%/*}/../../dev/lib/utils.sh"

export CROSS_COMPILE="${CROSS_COMPILE:?}"
export BUILD_TIME="${BUILD_TIME:?}"
export TASK_NAME="${TASK_NAME:?}"
export TASK_DIR="${TASK_DIR:?}"
export BUILD_DIR="${BUILD_DIR:?}"
export INSTALL_DIR="${INSTALL_DIR:?}"
export OUT_DIR="${OUT_DIR:?}"

build_dir="$(abspath "${BUILD_DIR}")"
install_dir="$(abspath "${INSTALL_DIR}")"
out_dir="$(abspath "${OUT_DIR}")"

mkdir -p "${build_dir}" "${install_dir}"
pushd "${TASK_DIR}" >/dev/null
{
  declare -x CC="ccache ${GCC}"
  declare -x CXX="ccache ${GXX}"

  declare -x CFLAGS="${CFLAGS:-} -O3 -finline-functions -funroll-loops -Wall -fopenmp"
  declare -x LDFLAGS="${LDFLAGS:-} -lm"

  nicely prefix="${install_dir}" build_dir="${build_dir}" make -s -j$(nproc) install 2>&1 | log "${build_dir}/build.log"

  version="$(sed -n '1p' version.txt)"
  date="$(sed -n '2p' version.txt)"
  VERSION="${version}-${date}"

  package_all "${install_dir}" "${out_dir}/${TASK_NAME}-${VERSION}-static-${CROSS_COMPILE}-${BUILD_TIME}"
}
popd >/dev/null
