#!/usr/bin/env bash
# shellcheck disable=SC2155
set -euo pipefail
trap "exit" INT
# shellcheck source=./../../dev/lib/utils.sh
source "${BASH_SOURCE%/*}/../../dev/lib/utils.sh"

export CROSS_COMPILE="${CROSS_COMPILE:?}"
export BUILD_TIME="${BUILD_TIME:?}"
export TASK_NAME="${TASK_NAME:?}"
export TASK_DIR="${TASK_DIR:?}"
export BUILD_DIR="${BUILD_DIR:?}"
export INSTALL_DIR="${INSTALL_DIR:?}"
export OUT_DIR="${OUT_DIR:?}"

NAME="${TASK_NAME}"
REPO_URL="https://github.com/stamatak/standard-RAxML"
VERSION="8.2.13"

build_dir="$(abspath "${BUILD_DIR}")"
install_dir="$(abspath "${INSTALL_DIR}")"
out_dir="$(abspath "${OUT_DIR}")"

mkdir -p "${build_dir}" "${install_dir}"
pushd "${build_dir}" >/dev/null
{
  src_dir="${NAME}-${VERSION}"

  if [ ! -d "${src_dir}" ]; then
    nicely git clone --quiet --recursive --depth=1 -b "v${VERSION}" "${REPO_URL}" "${src_dir}"
  fi

  pushd "${src_dir}" >/dev/null
  {
    export CC="ccache ${CC}"
    export CXX="ccache ${CXX}"

    ext=""
    case "${CROSS_COMPILE}" in
    x86_64-unknown-linux-*)
      flavor="AVX.PTHREADS.gcc"
      export CFLAGS="-D_USE_PTHREADS -D__SIM_SSE3 -D__AVX -D_GNU_SOURCE -msse3 -mavx ${CFLAGS}"
      ;;
    x86_64-pc-windows-gnu)
      flavor="AVX.PTHREADS.gcc"
      export CFLAGS="-D_USE_PTHREADS -D__SIM_SSE3 -D__AVX -D_GNU_SOURCE -msse3 -mavx ${CFLAGS}"
      ext=".exe"
      ;;
    aarch64-unknown-linux-*)
      flavor="SSE3.PTHREADS.gcc"
      export CFLAGS="-D_USE_PTHREADS -D_GNU_SOURCE ${CFLAGS}"
      ;;
    x86_64-apple-darwin)
      flavor="AVX.PTHREADS.mac"
      export CFLAGS="-D_USE_PTHREADS -D__SIM_SSE3 -D__AVX -D_GNU_SOURCE -msse3 -mavx ${CFLAGS}"
      ;;
    aarch64-apple-darwin)
      flavor="SSE3.PTHREADS.gcc"
      export CFLAGS="-D_USE_PTHREADS -D_GNU_SOURCE ${CFLAGS}"
      ;;
    esac

    sed -i 's|CC =|CC ?=|g' "Makefile.${flavor}"
    sed -i "s|CFLAGS =|CFLAGS ?=|g" "Makefile.${flavor}"

    nicely make -s -j$(nproc) -f "Makefile.${flavor}" 2>&1 | log "${build_dir}/build.log"

    find . -maxdepth 1 -type f -name 'raxmlHPC-*' -executable -exec \
      install -D -m 755 -s --strip-program=${STRIP:-strip} {} "${install_dir}/bin/raxml${ext}" \;

    package_all "${install_dir}" "${out_dir}/${NAME}-${VERSION}-static-${CROSS_COMPILE}-${BUILD_TIME}"
  }
  popd >/dev/null
}
popd >/dev/null
