#!/usr/bin/env bash
# shellcheck disable=SC2155
set -euo pipefail
trap "exit" INT
# shellcheck source=./../../dev/lib/utils.sh
source "${BASH_SOURCE%/*}/../../dev/lib/utils.sh"

export CROSS_COMPILE="${CROSS_COMPILE:?}"
export BUILD_TIME="${BUILD_TIME:?}"
export TASK_NAME="${TASK_NAME:?}"
export TASK_DIR="${TASK_DIR:?}"
export BUILD_DIR="${BUILD_DIR:?}"
export INSTALL_DIR="${INSTALL_DIR:?}"
export OUT_DIR="${OUT_DIR:?}"

NAME="${TASK_NAME}"
REPO_URL="https://github.com/lh3/minimap2"
VERSION="2.28"

build_dir="$(abspath "${BUILD_DIR}")"
install_dir="$(abspath "${INSTALL_DIR}")"
out_dir="$(abspath "${OUT_DIR}")"

mkdir -p "${build_dir}" "${install_dir}" "${out_dir}"
pushd "${build_dir}" >/dev/null
{
  src_dir="${NAME}-${VERSION}"

  if [ ! -d "${src_dir}" ]; then
    nicely git clone --quiet --recursive --depth=1 -b "v${VERSION}" "${REPO_URL}" "${src_dir}"
  fi

  pushd "${src_dir}" >/dev/null
  {
    ext=""
    case "${CROSS_COMPILE}" in
    aarch64* )
      export aarch64="1"
    ;;
    *mingw* | *windows* )
      export ext=".exe"
    ;;
    esac

    sed -i "s|CFLAGS=|CFLAGS ?=|g" "Makefile"
    sed -i "s|CPPFLAGS=|CPPFLAGS ?=|g" "Makefile"
    sed -i "s|LIBS=|LIBS ?=|g" "Makefile"

    export LDFLAGS="$(printf -- '-L%s ' ${LIBRARY_PATH//:/ }) ${LDFLAGS}"
    export LIBS="-lm -lz -lpthread ${LDFLAGS}"

    nicely make -s -j$(nproc) 2>&1 | log "${build_dir}/build.log"

    nicely install -D -m 0644 "libminimap2.a" "${install_dir}/lib/libminimap2.a"
    nicely install -D -m 0644 "minimap.h" "${install_dir}/include/minimap.h"
    nicely install -D -m 0644 "minimap2.1" "${install_dir}/share/man/minimap2.1"
    nicely install -D -m 0755 -s --strip-program="${STRIP:-strip}" "minimap2${ext}" "${install_dir}/bin/minimap2${ext}"

    mkdir -p "${install_dir}/lib/pkgconfig"
cat <<EOF > "${install_dir}/lib/pkgconfig/minimap2.pc"
prefix=\${pcfiledir}/../..
exec_prefix=\${prefix}
libdir=\${exec_prefix}/lib
includedir=\${prefix}/include

Name: minimap2
Description: A fast and accurate sequence mapping and alignment tool
Version: ${VERSION}
Libs: -L\${libdir} -lminimap2
Cflags: -I\${includedir}
EOF

    package_all "${install_dir}" "${out_dir}/${NAME}-${VERSION}-static-${CROSS_COMPILE}-${BUILD_TIME}"
  }
  popd >/dev/null
}
popd >/dev/null
